(() => {
'use strict';
const DATA = window.UNIT_DATA;
const state={unit:null,i:0,answers:[],left:900,timer:null,score:0};
const $=id=>document.getElementById(id), app=()=>$('unitTestApp');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tm=s=>`${String(Math.floor(Math.max(0,s)/60)).padStart(2,'0')}:${String(Math.max(0,s)%60).padStart(2,'0')}`;
function styles(){
const s=document.createElement('style');s.textContent=`
.ut-wrap{max-width:1180px;margin:auto;padding:28px 18px 70px}.ut-hero,.ut-card,.ut-top,.ut-map,.ut-panel,.ut-result,.ut-review{background:#fff;border:1px solid #e5e7eb;border-radius:20px}.dark .ut-hero,.dark .ut-card,.dark .ut-top,.dark .ut-map,.dark .ut-panel,.dark .ut-result,.dark .ut-review{background:#0f172a;border-color:#334155;color:#e2e8f0}
.ut-hero{padding:34px}.ut-kicker{font-size:11px;font-weight:900;letter-spacing:.12em;color:#64748b}.ut-hero h1{margin:8px 0;font-size:38px}.ut-hero p{color:#64748b;line-height:1.8}.dark .ut-hero p{color:#94a3b8}.ut-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px;margin-top:18px}
.ut-card{text-align:left;padding:22px;cursor:pointer;transition:.18s}.ut-card:hover{transform:translateY(-3px);box-shadow:0 15px 32px rgba(15,23,42,.08)}.ut-card h2{margin:8px 0;font-size:21px}.ut-card p{margin:0;color:#64748b;font-size:13px;line-height:1.7}.dark .ut-card p{color:#94a3b8}.ut-tag{font-size:10px;font-weight:900;color:#94a3b8}
.ut-top{display:flex;align-items:center;gap:14px;padding:14px 18px;margin-bottom:18px}.ut-sub{font-size:12px;font-weight:900}.ut-unit{flex:1;font-weight:900}.ut-timer{font-size:24px;font-weight:950}.ut-timer.warn{color:#dc2626}.ut-btn{border-radius:10px;padding:9px 14px;font-weight:900;cursor:pointer}.ut-outline{border:1px solid #d1d5db;background:#fff;color:#111}.dark .ut-outline{background:#0f172a;border-color:#475569;color:#e2e8f0}.ut-primary{background:#111827;border:1px solid #111827;color:#fff}.dark .ut-primary{background:#f8fafc;border-color:#f8fafc;color:#0f172a}
.ut-shell{display:grid;grid-template-columns:235px 1fr;gap:18px}.ut-map{height:max-content;padding:18px;position:sticky;top:88px}.ut-map h3{margin:0 0 12px}.ut-qgrid{display:grid;grid-template-columns:repeat(5,1fr);gap:7px}.ut-q{border:1px solid #d1d5db;background:#fff;border-radius:9px;padding:8px 0;font-size:11px;font-weight:800;cursor:pointer}.dark .ut-q{background:#111827;color:#e2e8f0;border-color:#475569}.ut-q.current{background:#111827;color:#fff}.ut-q.done:not(.current){background:#eff6ff;color:#1d4ed8}.dark .ut-q.done:not(.current){background:#172554;color:#bfdbfe}.ut-note{margin-top:14px;font-size:10px;color:#94a3b8;line-height:1.7}
.ut-panel{padding:32px;min-height:520px}.ut-num{font-size:11px;font-weight:900;color:#94a3b8;letter-spacing:.13em}.ut-type{display:inline-block;margin:9px 0;padding:4px 8px;border-radius:999px;background:#f3f4f6;color:#374151;font-size:10px;font-weight:900}.dark .ut-type{background:#1f2937;color:#d1d5db}.ut-panel h2{font-size:24px;line-height:1.75;margin:10px 0 28px}.ut-choices{display:grid;gap:11px}.ut-choice{display:flex;gap:12px;padding:15px;border:1px solid #e5e7eb;border-radius:12px;background:#fff;cursor:pointer}.dark .ut-choice{background:#0b1220;border-color:#334155}.ut-choice.selected{background:#eff6ff;border-color:#2563eb}.dark .ut-choice.selected{background:#172554;border-color:#3b82f6}.ut-key{font-weight:900;min-width:24px}.ut-actions{display:flex;justify-content:space-between;margin-top:30px}
.ut-result{padding:40px;text-align:center}.ut-score{font-size:58px;font-weight:950;margin:18px 0}.ut-result p{color:#64748b}.dark .ut-result p{color:#94a3b8}.ut-review{margin-top:18px;padding:24px}.ut-review-item{padding:14px 0;border-bottom:1px solid #e5e7eb}.dark .ut-review-item{border-color:#334155}.ok{color:#047857;font-weight:900}.bad{color:#b91c1c;font-weight:900}.muted{color:#64748b;font-size:12px;line-height:1.7}.dark .muted{color:#94a3b8}
@media(max-width:850px){.ut-grid,.ut-shell{grid-template-columns:1fr}.ut-map{position:static}.ut-panel{padding:22px}.ut-top{flex-wrap:wrap}.ut-timer{margin-left:auto}}@media(max-width:600px){.ut-wrap{padding:20px 12px 50px}.ut-hero{padding:24px}.ut-hero h1{font-size:31px}.ut-panel h2{font-size:20px}}
`;document.head.appendChild(s)}
function theme(){const h=document.documentElement,b=$('themeToggleBtn'),i=$('themeIcon');if(localStorage.theme==='dark')h.classList.add('dark');const sync=()=>{if(i)i.textContent=h.classList.contains('dark')?'☀':'☾'};if(b)b.onclick=()=>{h.classList.toggle('dark');localStorage.theme=h.classList.contains('dark')?'dark':'light';sync()};sync()}
function home(){stop();state.unit=null;state.i=0;app().innerHTML=`<div class="ut-wrap"><section class="ut-hero"><div class="ut-kicker">${esc(DATA.title).toUpperCase()}</div><h1>${esc(DATA.title)}</h1><p>한 단원만 선택해 집중적으로 평가합니다. 단원별 5문제 · 15분 · 제출 후 바로 채점과 해설을 확인할 수 있습니다.</p></section><div class="ut-grid">${DATA.units.map(u=>`<button class="ut-card" onclick="unitStart('${u.id}')"><div class="ut-tag">5 QUESTIONS · 15 MIN</div><h2>${esc(u.title)}</h2><p>${esc(u.desc)}</p></button>`).join('')}</div></div>`}
function start(id){const u=DATA.units.find(x=>x.id===id);if(!u||u.questions.length!==5){alert('단원평가 데이터 오류가 있습니다.');return}stop();state.unit=id;state.i=0;state.answers=Array(5).fill(null);state.left=900;render();state.timer=setInterval(()=>{state.left--;updateTimer();if(state.left<=0)submit(true)},1000)}
function stop(){if(state.timer){clearInterval(state.timer);state.timer=null}} function updateTimer(){const e=$('utTimer');if(e){e.textContent=tm(state.left);e.classList.toggle('warn',state.left<=180)}} function unit(){return DATA.units.find(u=>u.id===state.unit)}
function map(u){return `<aside class="ut-map"><h3>문제 번호</h3><div class="ut-qgrid">${u.questions.map((_,i)=>`<button class="ut-q ${i===state.i?'current ':''}${state.answers[i]!==null?'done':''}" onclick="unitGoto(${i})">${i+1}</button>`).join('')}</div><div class="ut-note">진한색: 현재 문제<br>파란색: 답안 선택<br>3분 전부터 시간 경고</div></aside>`}
function render(){const u=unit(),q=u.questions[state.i];app().innerHTML=`<div class="ut-wrap"><div class="ut-top"><span class="ut-sub">${esc(DATA.title.replace(' 단원평가',''))}</span><span class="ut-unit">${esc(u.title)}</span><button class="ut-btn ut-outline" onclick="unitHome()">단원 선택</button><div><div class="ut-kicker">남은 시간</div><div id="utTimer" class="ut-timer">${tm(state.left)}</div></div></div><div class="ut-shell">${map(u)}<main class="ut-panel"><div class="ut-num">QUESTION ${String(state.i+1).padStart(2,'0')} / 05</div><span class="ut-type">${esc(q[4])}</span><h2>${esc(q[0])}</h2><div class="ut-choices">${q[1].map((c,j)=>`<label class="ut-choice ${state.answers[state.i]===j?'selected':''}" onclick="unitPick(${j})"><input type="radio" name="choice" ${state.answers[state.i]===j?'checked':''}><span class="ut-key">${String.fromCharCode(65+j)}</span><span>${esc(c)}</span></label>`).join('')}</div><div class="ut-actions"><button class="ut-btn ut-outline" onclick="unitPrev()" ${state.i===0?'disabled':''}>← 이전</button>${state.i===4?'<button class="ut-btn ut-primary" onclick="unitSubmit()">답안 제출</button>':'<button class="ut-btn ut-primary" onclick="unitNext()">다음 →</button>'}</div></main></div></div>`;updateTimer()}
function pick(j){state.answers[state.i]=j;render()} function next(){if(state.i<4){state.i++;render()}} function prev(){if(state.i>0){state.i--;render()}} function gotoQ(i){if(i>=0&&i<5){state.i=i;render()}} function submitAsk(){if(confirm('답안을 제출하시겠습니까?'))submit(false)}
function submit(auto){if(!state.unit)return;stop();const u=unit();state.score=u.questions.reduce((n,q,i)=>n+(state.answers[i]===q[2]?1:0),0);const a=state.answers.filter(v=>v!==null).length;app().innerHTML=`<div class="ut-wrap"><section class="ut-result"><div class="ut-kicker">${auto?'TIME LIMIT REACHED':'UNIT TEST COMPLETE'}</div><h1>${esc(u.title)}</h1><div class="ut-score">${state.score*20}점</div><p>5문제 중 ${state.score}문제 정답 · ${a}문제 응답 · ${5-a}문제 미응답</p><div style="display:flex;justify-content:center;gap:10px;margin-top:22px"><button class="ut-btn ut-outline" onclick="unitHome()">다른 단원</button><button class="ut-btn ut-primary" onclick="unitReview()">문제별 해설</button></div></section><div id="reviewMount"></div></div>`}
function review(){const u=unit(),m=$('reviewMount');if(!m)return;m.innerHTML=`<section class="ut-review"><h2>정답 및 해설</h2>${u.questions.map((q,i)=>{const ok=state.answers[i]===q[2],mine=state.answers[i]===null?'미응답':q[1][state.answers[i]];return `<div class="ut-review-item"><strong>${i+1}. ${esc(q[0])}</strong><div class="${ok?'ok':'bad'}">${ok?'정답':'오답'}</div><div class="muted">내 답: ${esc(mine)} · 정답: ${esc(q[1][q[2]])}<br>해설: ${esc(q[3])}</div></div>`}).join('')}</section>`;m.scrollIntoView({behavior:'smooth'})}
window.unitStart=start;window.unitPick=pick;window.unitNext=next;window.unitPrev=prev;window.unitGoto=gotoQ;window.unitHome=home;window.unitSubmit=submitAsk;window.unitReview=review;document.addEventListener('DOMContentLoaded',()=>{styles();theme();home()});
})();